// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.DAL.Models;

public partial class OrderPromotion
{
    [Key]
    [Column("OrderPromotionID")]
    public int OrderPromotionId { get; set; }

    [Column("OrderID")]
    public int? OrderId { get; set; }

    [Column("PromotionID")]
    public int? PromotionId { get; set; }

    public double? DiscountValue { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderPromotions")]
    public virtual Order Order { get; set; }

    [ForeignKey("PromotionId")]
    [InverseProperty("OrderPromotions")]
    public virtual Promotion Promotion { get; set; }
}