// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.DAL.Models;

[Table("UserAnswer")]
public partial class UserAnswer
{
    [Key]
    [Column("AnswerID")]
    public int AnswerId { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    [Column("QuestionID")]
    public int? QuestionId { get; set; }

    [StringLength(50)]
    public string AnswerText { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("UserAnswers")]
    public virtual SkinTypeQuestion Question { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserAnswers")]
    public virtual User User { get; set; }
}